[
    {
        "id": 55,
        "line": 439,
        "precode": "        throw new SmartNullPointerException(join(",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "        throw new SmartNullPointerException(format("
    },
    {
        "id": 56,
        "line": 440,
        "precode": "                \"You have a NullPointerException here:\",",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "        throw new SmartNullPointerException(join(\",\","
    },
    {
        "id": 60,
        "line": 445,
        "precode": "                \"\"",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "                location,"
    },
    {
        "id": 61,
        "line": 56,
        "precode": "        throw new MockitoException(join(",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "        throw new MockitoException(format("
    },
    {
        "id": 62,
        "line": 57,
        "precode": "                \"Cannot stub with null throwable!\"",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "        throw new MockitoException(join(\""
    },
    {
        "id": 65,
        "line": 422,
        "precode": "        throw new InvalidUseOfMatchersException(join(",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "        throw new InvalidUseOfMatchersException(format("
    },
    {
        "id": 66,
        "line": 423,
        "precode": "                \"Misplaced argument matcher detected here:\",",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "        throw new InvalidUseOfMatchersException(join(\",\","
    },
    {
        "id": 71,
        "line": 431,
        "precode": "                \"\",",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "                \"    verify(mock).someMethod(contains(\\\\\"foo\\\\\"))\",\"\","
    },
    {
        "id": 74,
        "line": 434,
        "precode": "                \"\"",
        "filepath": "/mnt/disk1/cmd/defects4j_fixed/Mockito/Mockito_30_fixed/src/org/mockito/exceptions/Reporter.java",
        "aftercode": "                \"Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().\",//"
    }
]